### ISSUE TITLE
Re-organize repo

### ISSUE THREAD

**Issue by rcuevass** [schneidrew/fitter-testing#1]
@schneidrew 
Add the following folders to the repo and put in each folder the corresponding elements.
When doing so, create a new branch with a name that reflects the task. E.g. `reorganize-repo` or something along those lines.

- `code`
   -- `scripts` (as it suggests, add the *.py files)
   -- `notebooks` (as it suggested, add *.ipynb files)

-  `data`
    -- `input` (data to be consumed by your notebooks/scripts)
    -- `output` (data to be generated by your notebooks/scripts)

-  `references` (to keep track of whitepapers, papers, notes, etc)

     -- `references` (in case you decide to add papers, whitepapers, etc)
     -- `notes` (here you can include notes you have generated or something similar)
     -- `plots` (it is good practice to save the plots generated by your scripts/notebooks) to file

**Important**. When creating folders and moving files around make sure to use version control. E.g. `git mv my_file.py` code\scripts\ etc. 
Let me know if you are in doubt.

**Comment by schneidrew** [comment]
I've created the folders in the repository, and moved files to be in their respective folders. I've done this in the branch "organize-repo" which I have not yet merged with the master branch

**Comment by rcuevass** [comment]
@schneidrew . Nice job.
Please:
-  under `code` folder add an extra level for scripts: `code/scripts/` and put under it the `.py` versions of your notebooks. It is much easier for a reviewer to add comments and suggestions on a `.py` script as opposed to on a notebook.

- add `README` files for each folder. This is, one `README.md` for `data` folder and another one for `code`. In each add a brief explanation of what the data and code, respectively, are about

**Comment by schneidrew** [comment]
@rcuevass 
I've completed both of the requests you've made:

- There are now '.py' scripts in the `code/scripts/` folder that are equivalent to the '.ipynb' notebook files in the 'code/notebooks/' folder

- I have added 'README.md' files in both the 'data' and 'code' folders, describing the contents of each folder
